#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=01
start_service() {
    procd_open_instance
    # todo load from conf
    procd_set_param command /srv/ddnsd -listen-dns 46.118.105.211:53 --listen-api=46.118.105.211:8080 --self-ip=46.118.105.211 --self-domain=dyn.jkl.mn. --verbose
    procd_set_param stderr 1
    procd_set_param stdout 1
    procd_close_instance
}

